version: "3.9"

networks:
  bytebreacher:
    driver: bridge

services:
  docs:
    hostname: bb_docs
    container_name: bb_docs
    build:
      context: ./containers/docs/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docs/
        target: /var/www/html
        bind:
          create_host_path: true
    networks:
      - bytebreacher
